---
title: "Plastic"
author: "Yun He, Jun Lu, Chu Yu, Chunxiao Zhai, Haoran Hu"
date: "11/21/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(SASxport)
knitr::opts_chunk$set(
    fig.align = 'center',
    fig.width = 7,
    fig.asp = 0.6,
    out.width = "80%",
    message = F,
    warning = F
 )
theme_set(theme_bw() + theme(legend.position = "bottom"))


```

## Overview

## Read and clean the data
```{r}
phthte_file_name = tibble(file_name = list.files("./data/PHTHTE/"))

phthte =
  phthte_file_name %>% 
  mutate(map(str_c("./data/PHTHTE/", file_name), ~read.xport(.x))) %>% 
  unnest() 
    
demo_file_name = tibble(file_name_2 = list.files("./data/DEMO/"))

demo = 
    demo_file_name %>% 
    mutate(map(str_c("./data/DEMO/", file_name_2), ~read.xport(.x))) %>% 
    unnest()

phthte_demo = inner_join(demo, phthte, by = "SEQN") %>%
  select(year = file_name, gender = RIAGENDR, age = RIDAGEYR, race = RIDRETH3, weight = WTMEC2YR, 
         income = INDFMPIR, pregnancy_status = RIDEXPRG, MEP = URXMEP, MnBP = URXMBP, 
         MiBP = URXMIB, MCPP = URXMC1, MBzP = URXMZP, MEHP = URXMHP, MEHHP = URXMHH, MEOHP = URXMOH) %>%
  mutate(phthte_all = MEP + MnBP + MiBP + MCPP + MBzP + MEHP + MEHHP + MEHHP,
         race = factor(race, levels = c(1, 2, 3, 4, 6, 7), labels = c("mexican_american", "other_hispanic",
                                    "non_hispanic_white", "non_hispanic_black", "non_hispanic_asian", "other_race")),
         pregnancy_status = factor(pregnancy_status, levels = c(1, 2, 3), labels = c("yes", "no", "unknown")),
         gender = factor(gender, levels = c(1,2), labels = c("male", "female")),
         year = str_remove(year, "PHTHTE_"),
         year = str_remove(year, ".XPT")) %>%
  gather(key = "phthe", value = "concen_value", MEP:phthte_all) %>% 
  mutate(log_value = log(concen_value)) %>% 
  filter(!is.na(concen_value))
```

## Exploratory analysis

## Tendency analysis
```{r}
pd_tend = phthe_demo %>%
  group_by(year) %>%
  summarize(total = n(),
            proportion = length(which(phthe_combin == 1))/total)

pd_tend %>%
  ggplot(aes(x = year, y = proportion)) +
  geom_histogram(stat = "identity")

phthe_demo %>%
  ggplot(aes(x = year, y = phthe, fill = factor(year))) +
  geom_violin()
```

## Population compare

```{r}
phthte_by_year = phthte_demo %>% 
  select(year, gender, race, age, phthe) %>% 
  nest(gender:phthe)


gender_race_plot = function(year, gender_race_data) {
   gender_race_data %>% 
   mutate(gender = as.factor(gender),
          race = as.factor(race)) %>% 
   mutate(race = forcats::fct_reorder(race, gender_race_data$phthe)) %>% 
   ggplot(aes(x = race, y = phthe, fill = gender)) + 
     geom_boxplot() + 
     labs(title = str_c("Urine phthte level of differnet gender and race group in ", year), y = "Urine phthte level") +
     theme(axis.text.x = element_text(face = "plain", color = "black", size = 10, angle = 30,hjust = 1))
 }

gender_race_plot(phthe_by_year[[1,1]],phthe_by_year$data[[1]])

age_phthte_plot = function(year, age_data) {
  age_data %>% 
    mutate(age = cut(age,  breaks = c(0, 12, 18, 35, 55, Inf), labels = c("Young children(0-12ys)", "Teenagers(13-18ys)", "Young adults(19-35ys)", "Middle-aged adults(36-55ys)", "Older adults(>55ys)"))) %>% 
    ggplot(aes(x = age, y = phthe)) + 
    geom_boxplot(fill = "brown1") + 
    theme(axis.text.x = element_text(face = "plain", color = "black", size = 10, angle = 30,hjust = 1))
}
age_phthte_plot(phthe_by_year[[1,1]],phthe_by_year$data[[1]])

```

性别，种族，塑化剂随年龄变化


